### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by pombredanne** [Bluebird7/poptop#1]
kasra:
What would be the license of this fine piece of code?
Thanks!

**Comment by kasravnd** [comment]
Actually I didn't set any license for this code, I just asked a relative question in [StackApp](http://stackapps.com/questions/6194/is-there-any-app-that-could-extract-and-manage-questions-from-stack-overflow) and in SOMeta, and realized that users can extract this info (just raw info) with querying on SO database. And realized that it's legal :) , and since I just done this in a weekend I didn't thought about any licence.Feel free to fork and improve the repository.

**Comment by pombredanne** [comment]
FWIW, no license means that you give no permission to use the code, beyond just seeing the code.

**Comment by pombredanne** [comment]
See http://choosealicense.com/
